# 웹 서버 포트 설정 (Quasar 개발 서버)
# quasar build 후 spring boot와 같은 port를 사용하는 경우에는 삭제함.
# Spring Security의 Cors설정에서 allowed Origin에서 사용함.
webPort: 9000

# API 서버의 기본 URL (spring boot 수행port)
baseUrl: "http://localhost:9001/api"

# 웹 서버 기본 URL, quasar build 후 spring boot와 같은 port를 사용하는 경우에는 삭제함
# inicis 결제 후 return url에서 사용함
webBaseUrl: "http://localhost:9000"

# 첨부 화일(이미지) upload directory
file:
  upload-dir: ./main/resources/images/uploads

# JWT 관련 설정
jwt:
  secret: "1@Ml9demE7lEwK#zc3v5X!d29yM6s8@j#DYSycrhk0fYm1HdU!TyGv14SSIpdf"    # JWT 토큰 서명에 사용할 비밀 키
  accessTokenExpiration: 7200000                                              # Access Token의 유효 기간 (밀리초 기준, 2시간)
  refreshTokenExpiration: 864000000                                           # Refresh Token의 유효 기간 (밀리초 기준, 10일)
  cookieMaxAge: 86400                                                         # Refresh Token을 담은 쿠키의 유효 기간 (초 기준, 24시간)

# 카카오 알림톡 관련 설정
alimtalk:
  tokenUrl: https://www.biztalk-api.com/v2/auth/getToken       # 알림톡 API의 토큰 발급 URL
  sendUrl: https://www.biztalk-api.com/v2/kko/sendAlimTalk     # 알림톡 전송 API URL
  resultUrl: https://www.biztalk-api.com/v2/kko/getResultAll   # 알림톡 전송 결과 확인 URL
  bsid: wisam                                                  # 사용자의 고유 아이디
  passwd: b14c2d414288409ff3948159e1b9306c7c48a302             # 사용자의 비밀번호
  senderKey: 4946de9fe9945a158bf5b9a47c8bbc7e6d3ceeb5          # 발송용 인증 키
  templateCode: bidawardnotice                                 # 사용되는 템플릿 코드
  countryCode: "82"                                            # 국가 코드 (한국: 82)
  # excel로 제공된 정보 (현재 사용하지 않음)
  # clientId : "wisam"                                         # 사용하지 않는 클라이언트 아이디
  # clientSecret : "66fd8d80344a5bb4b28f85ee02cd378178bacf8e"  # 사용하지 않는 클라이언트 시크릿

# CoolSMS API 설정
coolsms:
  apiKey: "NCS547958B8DCD89"                                    # CoolSMS API 키
  apiSecretKey: "0FC78662787861FB62E9349FDA63A75B"              # CoolSMS API 시크릿 키
  provider: "https://api.coolsms.co.kr"                         # CoolSMS API 제공 URL
  sender: "024475967"                                           # 발신자 번호
  expirationTimeInMinutes: 3                                    # 인증번호 유효 시간 (분)
  # sendProfileKey : "66fd8d80344a5bb4b28f85ee02cd378178bacf8e" # 사용하지 않는 발송 프로필 키


# 이니시스 결제 및 승인 요청 설정
inicis:
  params:
    version: "1.0"                                              # API 버전
    mid: "INIpayTest"                                           # 상점 아이디
    currency: "WON"                                             # 거래 통화 (원화)
    acceptMethod: "HPP(1):va_receipt:below1000:centerCd(Y)"     # 허용 결제 수단 및 설정
    gopayMethod: "Card:DirectBank:VBank:HPP"                    # 허용 결제 방식
    signKey: "SU5JTElURV9UUklQTEVERVNfS0VZU1RS"                 # 이니시스 API 서명 키
    use_chkfake: "Y"                                            # 위변조 방지 여부

  idcName:
    fc: "fc"                                                    # FC 서버 이름
    ks: "ks"                                                    # KS 서버 이름
    stg: "stg"                                                  # STG 서버 이름

  returnUrls:
    return: "{baseUrl}/pgreturn"                                # PC 결제 완료 후 리턴 URL
    returnMobile: "{baseUrl}/pgreturn-mobile"                   # 모바일 결제 완료 후 리턴 URL
    close: "{baseUrl}/pgclose"                                  # 결제창 종료 URL
    redirect: "{webBaseUrl}/bidseats"                           # 결제 완료 후 리디렉션 URL
    login: "{webBaseUrl}/userlogin"                             # 로그인 리디렉션 URL

  views:
    request: "INIstdpay_pc_req"                                 # 결제창 요청 화면
    return: "INIstdpay_pc_return"                               # PC 결제 완료 화면
    requestMobile: "INImobile_mo_req"                           # 모바일 결제창 요청 화면
    returnMobile: "INImobile_mo_return"                         # 모바일 결제 완료 화면
    close: "close"                                              # 결제창 종료 화면
    error: "error"                                              # 결제 에러 화면

  urls:
    auth:
      fc: "https://fcstdpay.inicis.com/api/payAuth"              # FC 서버 인증 URL
      ks: "https://ksstdpay.inicis.com/api/payAuth"              # KS 서버 인증 URL
      stg: "https://stgstdpay.inicis.com/api/payAuth"            # STG 서버 인증 URL
      default: "https://defaultstdpay.inicis.com/api/payAuth"    # 기본 인증 URL

    netCancel:
      fc: "https://fcstdpay.inicis.com/api/netCancel"           # FC 서버 망 취소 URL
      ks: "https://ksstdpay.inicis.com/api/netCancel"           # KS 서버 망 취소 URL
      stg: "https://stgstdpay.inicis.com/api/netCancel"         # STG 서버 망 취소 URL
      default: "https://defaultstdpay.inicis.com/api/netCancel" # 기본 망 취소 URL

    mobilePayReq:
      fc: "https://fcmobile.inicis.com/smart/payReq.ini"        # FC 서버 모바일 결제 요청 URL
      ks: "https://ksmobile.inicis.com/smart/payReq.ini"        # KS 서버 모바일 결제 요청 URL
      stg: "https://stgmobile.inicis.com/smart/payReq.ini"      # STG 서버 모바일 결제 요청 URL
      default: "https://default.inicis.com/smart/payReq.ini"    # 기본 모바일 결제 요청 URL

